# docker-compose.yml
services:
  api-pandas:
    build: .
    container_name: benchmark-pandas
    command: uvicorn src.api.app_pandas:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data/raw/financial_options_1M.parquet
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  api-polars:
    build: .
    container_name: benchmark-polars
    command: uvicorn src.api.app_polars:app --host 0.0.0.0 --port 8001 --workers 1
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data/raw/financial_options_1M.parquet
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G